### ISSUE TITLE
Add Mirador translation files to Transifex

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#952]

**Comment by camillevilla** [comment]
We ideally want to use the Transifex GitHub integration for this. Transifex supports two types of JSON. 
https://docs.transifex.com/formats/json
https://docs.transifex.com/formats/json/structured-json

Example Mirador locale file: 
https://github.com/ProjectMirador/mirador/blob/master/src/locales/fr/translation.json

**Comment by camillevilla** [comment]
I set up a Transifex organization for Project Mirador.

Transifex's GitHub integration worked well out of the box with our locale files. We used the [KEYVALUEJSON format](https://docs.transifex.com/formats/json). 

Example integration config:
```yaml
filters:
  - filter_type: file
    file_format: KEYVALUEJSON
    source_language: en
    source_file: src/locales/en/translation.json
    translation_files_expression: src/locales/<lang>/translation.json
```

Pleasant side-effect: we can see how translation-complete all of Mirador's languages are in one UI. 

![dashboard with information on translation completeness per language](https://user-images.githubusercontent.com/5402927/80045493-6fa4a280-84bc-11ea-88ed-9458e9f78562.png)
